# Generated by Django 2.1.7 on 2019-03-14 04:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(default='default bio'),
        ),
    ]
