# Generated by Django 2.1.7 on 2019-03-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
